# Generated by Django 4.0.4 on 2022-05-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='decription',
            new_name='description',
        ),
    ]
